import Link from "next/link";
import { Kicker, SectionHead } from "@/components/ui";
import { getArenaStats, getStandings } from "@/lib/data";
import { formatNumber } from "@/lib/veto";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Standings — VETO",
  description: "Anonymous vaults ranked purely by crowd-weighted points earned in open debate.",
};

export default async function StandingsPage() {
  const [standings, stats] = await Promise.all([getStandings(50), getArenaStats()]);

  return (
    <div className="pb-10 pt-16">
      <Kicker>STANDINGS</Kicker>
      <h1 className="mt-7 max-w-[28ch] text-[34px] leading-[1.02] tracking-[-0.035em] text-white sm:text-[50px]">
        Ranked by reasoning alone — and by nothing else.
      </h1>
      <p className="mt-7 max-w-[78ch] text-[15px] leading-relaxed text-dim">
        These are anonymous vaults, not people. A vault is a handle generated by the system, bound to
        a sealed key, and credited only with points the chamber actually cast. There are no profiles,
        no biographies, no follower counts, and no way to buy a position on this page.
      </p>

      <div className="mt-12 grid grid-cols-2 gap-px border border-line bg-line sm:grid-cols-4">
        {[
          { label: "VAULTS RANKED", value: formatNumber(standings.length) },
          { label: "POINTS AWARDED", value: formatNumber(stats.pointsInCirculation) },
          { label: "VOTES ON RECORD", value: formatNumber(stats.votesOnRecord) },
          { label: "NARROWEST CHAMBER", value: formatNumber(stats.densestChamber) },
        ].map((item) => (
          <div key={item.label} className="bg-black px-5 py-5">
            <span className="label">{item.label}</span>
            <div className="data mt-3 text-[22px] leading-none text-white">{item.value}</div>
          </div>
        ))}
      </div>

      <section className="mt-16">
        <SectionHead
          index="01"
          title="The table."
          note="Points per chamber is shown without rank weighting — a vault that wins one hyper-dense room may sit above a vault that swept a broadcast."
        />
        {standings.length === 0 ? (
          <p className="mt-8 text-[13px] text-mute">
            No vault has accrued points yet.{" "}
            <Link href="/arena" className="text-white underline underline-offset-4">
              Enter a chamber
            </Link>
            .
          </p>
        ) : (
          <div className="mt-6 border border-line">
            <div className="hidden grid-cols-[0.5fr_1.6fr_1.1fr_0.9fr_1.1fr_1.1fr] gap-4 border-b border-line px-5 py-4 md:grid">
              {["RANK", "VAULT HANDLE", "TOTAL POINTS", "CHAMBERS", "RECORD", "PTS / CHAMBER"].map(
                (h) => (
                  <span key={h} className="label">
                    {h}
                  </span>
                ),
              )}
            </div>
            {standings.map((row) => (
              <div
                key={row.handle}
                className="grid grid-cols-2 gap-3 border-b border-line px-5 py-4 last:border-b-0 md:grid-cols-[0.5fr_1.6fr_1.1fr_0.9fr_1.1fr_1.1fr] md:gap-4"
              >
                <span className="data text-[12px] text-mute">
                  {String(row.rank).padStart(2, "0")}
                </span>
                <span className="data truncate text-[12px] text-white">
                  {row.handle}
                  {row.rank <= 3 ? <span className="ml-3 text-mute">◆</span> : null}
                </span>
                <span className="data text-[12px] text-white">
                  {formatNumber(row.totalPoints)}
                </span>
                <span className="data text-[12px] text-dim">{formatNumber(row.matchesPlayed)}</span>
                <span className="data text-[12px] text-dim">
                  {row.wins}W · {row.ties}T · {row.losses}L
                </span>
                <span className="data text-[12px] text-dim">
                  {formatNumber(row.matchesPlayed ? row.totalPoints / row.matchesPlayed : 0)}
                </span>
              </div>
            ))}
          </div>
        )}
      </section>

      <section className="mt-16">
        <SectionHead
          index="02"
          title="Why the table cannot be gamed."
          note="Four structural defences, all of them in the arithmetic rather than in a moderation queue."
        />
        <div className="mt-6 grid gap-px border border-line bg-line md:grid-cols-2 xl:grid-cols-4">
          {[
            {
              t: "ONE MIND, ONE VOTE",
              b: "Each vote is a hash of a per-browser token against the match. The same token cannot vote twice in the same room, and no vote is attributed to anything but the pool.",
            },
            {
              t: "DENSITY PUNISHES PADDING",
              b: "Flooding a chamber with friendly voters lowers the point value for everyone in it, including you. Stuffing the room is mathematically self-defeating.",
            },
            {
              t: "SMALL ROOMS ARE HARD TO BUY",
              b: "A clandestine chamber is worth more per vote, which makes it worth more to manipulate — except that every added shill vote discounts the very pool being gamed.",
            },
            {
              t: "IDENTITY HAS NO FIELD",
              b: "Not a name, not a handle, not a follower count enters the formula. Reputation cannot be loaded in, so it cannot be spent.",
            },
          ].map((item) => (
            <div key={item.t} className="bg-black p-6">
              <h3 className="label-bright leading-relaxed">{item.t}</h3>
              <p className="mt-4 text-[13px] leading-relaxed text-mute">{item.b}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
